/* eslint-disable max-len */
export const TEXT_DICTIONARY = {
    BRING_FORWARD: 'Bring Forward',
    SEND_BACKWARD: 'Send Backward',
    LOCK: 'Lock',
    UNLOCK: 'Unlock',
    COPY: 'Copy',
    DELETE: 'Delete',
    BUTTON: 'Button',
    COLLAPSABLE: 'Collapsable',
    DROPDOWN: 'Dropdown',
    TITLE: 'Title',
    ADD_IMAGE: 'Add Image',
    DEFAULT: 'Default',
    CUSTOM_IMAGES: 'Custom Images',
    IMAGE_OPACITY: 'Image Opacity',
    LOGO: 'Logo',
    SHOW_QR_CODE: 'Show QR Code',
    SHOW_LOGO_IN_QR: 'Show Logo in QR Code',
    ADD_LOGO: 'Add Logo',
    SHAPE_FILL: 'Shape Fill',
    SHAPE_OPACITY: 'Shape Opacity',
    COLLAPSE: 'Collapse',
    TEXT: 'Text',
    STROKE_WIDTH_AND_COLOR: 'Stroke Width & Color',
    NEW_TEMPLATE: 'New Template',
    CUSTOM_TEMPLATES: 'Custom Templates',
    PAGE_SIZE: 'Page size',
    BACKGROUND_COLOR: 'Background Color',
    BACKGROUND_IMAGE: 'Background Image',
    BACKGROUND_IMAGE_OPACITY: 'Background Image Opacity',
    CUTTING_GUIDE: 'Cutting Guide',
    ADD_TEXT: 'Add Text',
    HELP_TEXT: 'Help Text',
    BOLD: 'Bold',
    ITALIC: 'Italic',
    LINE_THROUGH: 'Line Through',
    UNDERLINE: 'Underline',
    LEFT_ALIGN: 'Left Align',
    CENTER_ALIGN: 'Center Align',
    RIGHT_ALIGN: 'Right Align',
    FONT_FAMILY: 'Font Family',
    TEXT_SIZE: 'Text Size',
    TEXT_COLOR: 'Text Color',
    TEXT_OPACITY: 'Text Opacity',
    UNDO: 'Undo',
    REDO: 'Redo',
    SHOW_BRANDING: 'Show Fixalert Branding',
    UNLOCK_PREMIUM_FEATURE_PARAGRAPH:
        'Unlock premium features to customize your QR code sticker by hiding the company logo and watermark. Upgrade your plan for full control over your design.',
    UPGRADE_PLAN: 'Upgrade your plan',
    PREMIUM_SETTINGS: 'premium settings',
    ZOOM_IN_OUT: 'Zoom In/Out',
    TEMPLATE: 'Template',
    IMAGE: 'Image',
    SHAPE: 'Shape',
    QR_CODE: 'QR Code',
    BRANDING: 'Branding',
    QR: 'QR',
    WHITE_LABEL: 'White-label',
    OPACITY: 'Opacity',
    ADD_SHAPES: 'Add shapes',
    SETTINGS: 'Settings',
    PLEASE_ADD_IMAGES: 'Please Add Images',
};
export const TEXT_DICTIONARY_RU = {
    BRING_FORWARD: 'Переместить вперёд',
    SEND_BACKWARD: 'Отправить назад',
    LOCK: 'Заблокировать',
    UNLOCK: 'Разблокировать',
    COPY: 'Копировать',
    DELETE: 'Удалить',
    BUTTON: 'Кнопка',
    COLLAPSABLE: 'Сворачиваемый',
    DROPDOWN: 'Выпадающий список',
    TITLE: 'Заголовок',
    ADD_IMAGE: 'Добавить изображение',
    DEFAULT: 'По умолчанию',
    CUSTOM_IMAGES: 'Пользовательские изображения',
    IMAGE_OPACITY: 'Прозрачность изображения',
    LOGO: 'Логотип',
    SHOW_QR_CODE: 'Показать QR-код',
    SHOW_LOGO_IN_QR: 'Показать логотип в QR-коде',
    ADD_LOGO: 'Добавить логотип',
    SHAPE_FILL: 'Заливка фигуры',
    SHAPE_OPACITY: 'Прозрачность фигуры',
    COLLAPSE: 'Свернуть',
    TEXT: 'Текст',
    STROKE_WIDTH_AND_COLOR: 'Толщина и цвет обводки',
    NEW_TEMPLATE: 'Новый шаблон',
    CUSTOM_TEMPLATES: 'Пользовательские шаблоны',
    PAGE_SIZE: 'Размер страницы',
    BACKGROUND_COLOR: 'Цвет фона',
    BACKGROUND_IMAGE: 'Фоновое изображение',
    BACKGROUND_IMAGE_OPACITY: 'Прозрачность фонового изображения',
    CUTTING_GUIDE: 'Контур для резки',
    ADD_TEXT: 'Добавить текст',
    HELP_TEXT: 'Текст подсказки',
    BOLD: 'Жирный',
    ITALIC: 'Курсив',
    LINE_THROUGH: 'Зачёркнутый',
    UNDERLINE: 'Подчёркнутый',
    LEFT_ALIGN: 'Выровнять по левому краю',
    CENTER_ALIGN: 'Выровнять по центру',
    RIGHT_ALIGN: 'Выровнять по правому краю',
    FONT_FAMILY: 'Шрифт',
    TEXT_SIZE: 'Размер текста',
    TEXT_COLOR: 'Цвет текста',
    TEXT_OPACITY: 'Прозрачность текста',
    UNDO: 'Отменить',
    REDO: 'Повторить',
    SHOW_BRANDING: 'Показать фирменный стиль Fixalert',
    UNLOCK_PREMIUM_FEATURE_PARAGRAPH:
        'Откройте премиум-функции для настройки вашей наклейки с QR-кодом, скрыв логотип и водяной знак компании. Обновите план для полного контроля над дизайном.',
    UPGRADE_PLAN: 'Обновить план',
    PREMIUM_SETTINGS: 'премиум настройки',
    ZOOM_IN_OUT: 'Масштабировать',
    TEMPLATE: 'Шаблон',
    IMAGE: 'Изображение',
    SHAPE: 'Фигура',
    QR_CODE: 'QR-код',
    BRANDING: 'Брендинг',
    QR: 'QR',
    WHITE_LABEL: 'Без бренда',
    OPACITY: 'Прозрачность',
    ADD_SHAPES: 'Добавить фигуры',
    SETTINGS: 'Настройки',
    PLEASE_ADD_IMAGES: 'Пожалуйста, добавьте изображения',
};
