import PropTypes from 'prop-types';

export const propTypes = {
    selectedTab: PropTypes.string.isRequired,
    onSetBackgroundColor: PropTypes.func.isRequired,
    canvasBackgroundColor: PropTypes.string,
    canvasBackgroundImage: PropTypes.string,
    onSetBackgroundImage: PropTypes.func.isRequired,
    shapeStrokeColor: PropTypes.string,
    shapeStrokeWidth: PropTypes.number,
    shapeFillColor: PropTypes.string,
    shapeOpacity: PropTypes.number,
    onChangeShapeStrokeColor: PropTypes.func.isRequired,
    onChangeShapeStrokeWidth: PropTypes.func.isRequired,
    onChangeShapeFill: PropTypes.func.isRequired,
    onChangeShapeOpacity: PropTypes.func.isRequired,
    selectedElement: PropTypes.object,
    onChangeBackgroundImageOpacity: PropTypes.func.isRequired,
    backgroundImageOpacity: PropTypes.number,
    imageStrokeWidth: PropTypes.number,
    imageStrokeColor: PropTypes.string,
    imageOpacity: PropTypes.number,
    onChangeImageStrokeWidth: PropTypes.func.isRequired,
    onChangeImageStrokeColor: PropTypes.func.isRequired,
    onChangeImageOpacity: PropTypes.func.isRequired,
    qrStrokeWidth: PropTypes.number,
    qrStrokeColor: PropTypes.string,
    qrOpacity: PropTypes.number,
    onChangeQrStrokeWidth: PropTypes.func.isRequired,
    onChangeQrStrokeColor: PropTypes.func.isRequired,
    onChangeQrOpacity: PropTypes.func.isRequired,
    defaultTextProps: PropTypes.object,
    onChangeTextProperty: PropTypes.func.isRequired,
    onSetPageSize: PropTypes.func.isRequired,
    selectedPageSize: PropTypes.object,
    translation: PropTypes.object.isRequired,
    uploadImageCallBack: PropTypes.func.isRequired,
    setLoadingUploadImage: PropTypes.func.isRequired,
    cuttingGuideStroke: PropTypes.number,
    cuttingGuideStrokeColor: PropTypes.string,
    onChangeCuttingGuideProp: PropTypes.func.isRequired,
};
